  server:
    port: 8080
  spring:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: ai181003
      initialSize: 5    # 下面为连接池的补充设置，应用到上面所有数据源中
      minIdle: 5        # 初始化大小，最小，最大
      maxActive: 20
      maxWait: 60000     # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL  # 配置一个连接在池中最小生存的时间，单位是毫秒
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSiz: 20
      filters: stat,wall,log4j    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  #设置mybatis
  mybatis:
  #  映射文件所在路径
    mapper-locations: classpath:mapper/*Mapper.xml
  #  config配置文件
  #  config-location: classpath:mybatis-config.xml
  #  POJO类所在路径
#    type-aliases-package: com.example.springbootmybatis
#  数据库表字段蛇形命名转驼峰命名
#    configuration:
#      map-underscore-to-camel-case: true
